apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-grafana
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster 
    path: grafana
  persistentVolumeReclaimPolicy: Retain