apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: default-prometheus-server
          servicePort: 80
