apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-prometheus-server
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster 
    path: gluster_volume/kube_vol/promethes-alertmanager
  persistentVolumeReclaimPolicy: Retain