apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-prometheus-alertmanager
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/alert"
