apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-prometheus-server
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/data"
