apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-prometheus-alertmanager
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster 
    path: gluster_volume/kube_vol/prometheus-alertmanager
  persistentVolumeReclaimPolicy: Retain