---
  - name: Helm Deploy node-problem-detector
    hosts: local
    become: no
    tasks:
    - name: Helm deploy grafana
      shell:
        cmd: helm upgrade --install npd ../node-problem-detector
  