---
  - name: Helm Deploy metrics-server
    hosts: local
    become: no
    tasks:
    - name: Helm deploy metrics-server
      shell:
        cmd: helm upgrade --install metricsserver ../metrics-server
  