---
- name: Helm Destroy
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Helm uninstall Ingress
    command: helm uninstall ingress
    ignore_errors: True
  
  - name: Helm uninstall Prometheus
    command: helm uninstall default
    ignore_errors: True

  - name: Delete manual hacks
    command: kubectl delete -f /home/brett/git/nuctestlab/prometheus/manual_hacks/
    ignore_errors: True

