---
- name: Kubernetes Setup
  hosts: 127.0.0.1
  connection: local
  tasks:
  
  - name: Install kubeadm
    become: yes 
    apt:
      name: kubeadm
      state: present
   
  - name: cgroupfs > systemd change.
    become: yes
    shell: 
      cmd: |
        # Install Docker CE
        ## Set up the repository:
        ### Install packages to allow apt to use a repository over HTTPS
        apt-get update && apt-get install -y \
        apt-transport-https ca-certificates curl software-properties-common gnupg2
    
        ### Add Docker’s official GPG key
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    
        ### Add Docker apt repository.
        add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) \
        stable"
    
        ## Install Docker CE.
        apt-get update;apt-get install -y \
        containerd.io=1.2.10-3 \
        docker-ce=5:19.03.4~3-0~ubuntu-$(lsb_release -cs) \
        docker-ce-cli=5:19.03.4~3-0~ubuntu-$(lsb_release -cs)
    
        # Setup daemon.
        cat > /etc/docker/daemon.json <<EOF
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "storage-driver": "overlay2"
        }
        EOF
      
        mkdir -p /etc/systemd/system/docker.service.d
        # Restart docker.
        systemctl daemon-reload
        systemctl restart docker
  
  - name: Disable swap.
    become: yes
    shell: sudo swapoff -a 

  - name: Run kubeadm
    become: yes
    shell: "kubeadm init --pod-network-cidr=10.244.0.0/16"
  
  - name: Setup kubeconfig
    become: yes
    become_user: brett
    shell: 
      cmd: |
        mkdir -p $HOME/.kube 
        rm $HOME/.kube/config 
        sudo cp -r -i /etc/kubernetes/admin.conf $HOME/.kube/config 
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
    args:
      executable: bash

  - name: Install flannel YAML
    become: yes
    shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml"